accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns=[
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.create_user, name='register'),
    path('users/', views.users_list, name='users'),
]

pollme/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('polls/', include('polls.urls', namespace="polls")),
    path('accounts/', include('accounts.urls', namespace="accounts")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path
from . import views

app_name = "polls"

urlpatterns = [
    path('list/', views.polls_list, name='list'),
    path('list/user/', views.list_by_user, name='list_by_user'),
    path('add/', views.polls_add, name='add'),
    path('edit/<int:poll_id>/', views.polls_edit, name='edit'),
    path('delete/<int:poll_id>/', views.polls_delete, name='delete_poll'),
    path('end/<int:poll_id>/', views.endpoll, name='end_poll'),
    path('edit/<int:poll_id>/choice/add/', views.add_choice, name='add_choice'),
    path('edit/choice/<int:choice_id>/', views.choice_edit, name='choice_edit'),
    path('delete/choice/<int:choice_id>/',
         views.choice_delete, name='choice_delete'),
    path('<int:poll_id>/', views.poll_detail, name='detail'),
    path('<int:poll_id>/vote/', views.poll_vote, name='vote'),
    path('<int:poll_id>/result/', views.poll_result, name='result'),
]

templates/includes/navbar.html
<nav class="navbar navbar-expand-sm navbar-light bg-light">
    <a class="navbar-brand" href=""><i class="fas fa-person-booth"></i></a>
    <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId"
        aria-controls="collapsibleNavId" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavId">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
                <strong><a class="nav-link" href="{% url 'home' %}">خانه</a></strong>
            </li>
            <li class="nav-item active">
                <strong><a class="nav-link" href="{% url 'polls:list' %}">نظرسنجی ها</a></strong>
            </li>
            {% if user.is_staff %}
            <li>
                <strong><a class="nav-link" href="{% url 'accounts:users' %}">لیست کاربران</a></strong>
            </li>
            {% endif %}
        </ul>
        <div class="navbar-nav ml-auto">
            {% if request.user.is_authenticated %}
            <strong><a class="nav-link" href="#">
            {% if user.is_staff %}
                {{ user.first_name }} {{ user.last_name }} (مدیر)
            {% else %}
                {{ user.first_name }} {{ user.last_name }} (والدین)
            {% endif %}
            </a></strong>
            <strong><a class="nav-link" href="{% url 'accounts:logout' %}">خروج</a></strong>
            {% else %}
            <strong><a class="nav-link"href="{% url 'accounts:login' %}">ورود</a></strong>
            <strong><a class="nav-link" href="{% url 'accounts:register' %}">ثبت نام</a></strong>
            {% endif %}
        </div>
    </div>
</nav>